# Jekyll configuration for www.webtrees.net

title: webtrees
email: fisharebest@gmail.com
description: >
  webtrees is a web application that allows you to publish your genealogy online,
  collaborate with family members and take control of your data.
url: "https://webtrees.github.io"
github_repo: webtrees/webtrees.github.io
edit_text: Edit this page
baseurl: ""
date_format: "%b %-d, %Y"
show_excerpts: true
collections:
  readme:
    output: true

# External accounts
github_username:  fisharebest/webtrees
google_analytics: UA-89628860-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
